###
# Registration
POST https://server.local:8443/api/rest/users/register
Content-Type: application/json

{
  "username": {{$uuid}},
  "password": "top-secret"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

POST https://server.local:8443/api/rest/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "god"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

POST https://server.local:8443/api/rest/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "god"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

GET https://server.local:8443/api/rest/users/2/cards
Authorization: od62N0b4Q8Bd7w/8/rEZybvla3B49iEBYtmFGy1xcwtMkgThcX7SHVg9FP4HNSjKhqXwi6hhHS7wr9hm5hneWQ==

###

GET https://server.local:8443/api/rest/cards/1
Authorization: od62N0b4Q8Bd7w/8/rEZybvla3B49iEBYtmFGy1xcwtMkgThcX7SHVg9FP4HNSjKhqXwi6hhHS7wr9hm5hneWQ==

###

GET https://server.local:8443/api/rest/cards/1
Authorization: Basic YWRtaW46Z29k

###

GET https://server.local:8443/api/rest/cards/1
Cookie: token=od62N0b4Q8Bd7w/8/rEZybvla3B49iEBYtmFGy1xcwtMkgThcX7SHVg9FP4HNSjKhqXwi6hhHS7wr9hm5hneWQ==; screen-size=1720x1080

###

POST https://server.local:8443/api/rest/users/2/cards
Authorization: od62N0b4Q8Bd7w/8/rEZybvla3B49iEBYtmFGy1xcwtMkgThcX7SHVg9FP4HNSjKhqXwi6hhHS7wr9hm5hneWQ==

###

DELETE https://server.local:8443/api/rest/cards/2
Authorization: od62N0b4Q8Bd7w/8/rEZybvla3B49iEBYtmFGy1xcwtMkgThcX7SHVg9FP4HNSjKhqXwi6hhHS7wr9hm5hneWQ==

###

POST https://server.local:8443/api/rest/cards/1/transfer
Authorization: od62N0b4Q8Bd7w/8/rEZybvla3B49iEBYtmFGy1xcwtMkgThcX7SHVg9FP4HNSjKhqXwi6hhHS7wr9hm5hneWQ==
Content-Type: application/json

{
  "to": 4,
  "amount": 6000
}

###

POST https://server.local:8443/api/rest/users/reset
Content-Type: application/json

{
  "username": "admin"
}

###

POST https://server.local:8443/api/rest/users/changepass
Content-Type: application/json

{
  "username": "admin",
  "password": "god",
  "resetCode": "748707"
}